const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
const SET_AUTH_CHECK_IS_LOADING = 'SET_AUTH_CHECK_IS_LOADING';
const INIT_COMPLETE = 'INIT_COMPLETE';

export default {
  SET_IS_AUTHENTICATED,
  SET_AUTH_CHECK_IS_LOADING,
  INIT_COMPLETE,
};
